# Generated by Django 3.2.7 on 2021-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('user', models.CharField(max_length=100, verbose_name='user')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
