# Generated by Django 3.2.7 on 2021-09-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0002_auto_20210908_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='id')),
                ('author', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
