# Generated by Django 3.2.7 on 2021-09-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0003_auto_20210914_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
